require 'angular_commit_lint/commit_check'
require 'angular_commit_lint/subject_pattern_check'
require 'angular_commit_lint/subject_cap_check'
require 'angular_commit_lint/subject_words_check'
require 'angular_commit_lint/subject_length_check'
require 'angular_commit_lint/subject_period_check'
require 'angular_commit_lint/empty_line_check'
require 'angular_commit_lint/plugin'
